<?php

function getKeywords()
{
    return [
        'generative',
        'art',
        'processing',
        'design',
        'nature',
        'code',
        'programming',
        'graphics',
        'opengl',
        'rendering',
        'interactivity',
        'openframeworks',
        'creative',
        'animation',
        'html5',
        'canvas',
        'chaos',
        'fractals',
        'ray',
        'tracing',
        'cookbook',
        'data-driven',
        'visual',
        'real-time',
        'shaders',
        'javascript',
        'physics',
        'math',
        'webgl',
        'magenta',
        'machine',
        'learning',
        'book',
        'shaders',
        'fundamentals',
        'learn',
        'scratchapixel',
        'ofbook',
        'ogldev',
        'tutorial',
        'pixel',
        'projects',
        'algorithms',
        'computer',
        'bézier',
        'curves',
        'game',
        'xem',
        'creative',
        'coding',
        'notebooks',
        'academy',
        'create',
        'graphics',
        'js',
        'webgl',
        'learn',
        'html5',
        'animation',
        'interactive',
        'computer',
        'coursera',
        'kadenze',
        'processingjs',
        'processing',
        'visualization',
        'art',
        'canvas',
        'shaders',
        'three.js',
        'rust',
        'clojure',
        'c++',
        'swift',
        'metal',
        'rust',
        'cinder',
        'openframeworks',
        'unity',
        'godot',
        'playcanvas',
        'hype',
        'nannou',
        'thi.ng',
        'phaser',
        'vvvv',
        'visualscript',
        'nodebox',
        'touchdesigner',
        'quartz',
        'vuo',
        'max',
        'pure',
        'ossia',
        'tooll',
        'xod',
        'isadora',
        'cables',
        'eternal',
        'notch',
        'synopsis',
        'joy.js',
        'pixel',
        'nodes',
        'supercollider',
        'chuck',
        'tidalcycles',
        'sonic pi',
        'csound',
        'orca',
        'handel',
        'melrōse',
        'three.js',
        'regl',
        'stackgl',
        'paper.js',
        'pixi.js',
        'p5.js',
        'pts.js',
        'fabric.js',
        'maker.js',
        'openjscad',
        'sketch.js',
        'two.js',
        'claygl',
        'proton',
        'lightgl.js',
        'picogl.js',
        'alfrid',
        'babylon.js',
        'twigl',
        'luma.gl',
        'css-doodle',
        'ogl.js',
        'zdog',
        'oimo.js',
        'ammo.js',
        'theatre.js',
        'graphicsjs',
        'madmapper',
        'vdmx',
        'modul8',
        'resolume',
        'coge vj',
        'virtualmapper',
        'millumin',
        'smode',
        'veejay',
        'shadertoy',
        'shader park',
        'glslbin',
        'glsl sandbox',
        'shdr editor',
        'codepen',
        'shadershop',
        'vertexshaderart',
        'cyos',
        'glsleditor',
        'openprocessing',
        'p5.js editor',
        'livecodelab',
        'turtletoy',
        'shadergif',
        'p5live',
        'neort',
        'shelly',
        'tixy.land',
        'bbc micro bot',
        'arduino',
        'raspberry pi',
        'puck.js',
        'beagleboard',
        'makey makey',
        'tessel',
        'leap motion',
        'axidraw',
        'phidgets',
        'teensy',
        'lightform',
        'structure synth',
        'f3',
        'fragment',
        'shadertool',
        'syphon',
        'kode life',
        'isf',
        'glslviewer',
        'drawbot',
        'klak',
        'basil.js',
        'konstrukt',
        'the coding train',
        'mfgd',
        'shaders laboratory',
        'pen',
        'plotter',
        'art',
        'algorithms',
        'javascript',
        'noise',
        'creative',
        'coding',
        'unity',
        'programs',
        'ios',
        'c4',
        'particle',
        'physics',
        'visualization',
        'game development',
        'random numbers',
        'game programming',
        'generative artwork',
        'color',
        'shader',
        'webgl',
        'raytracing',
        'marching',
        'glsl',
        'canvas',
        'glossary',
        'computer graphics',
        'math',
        'subreddits',
        'slack',
        'podcast',
        'real time vfx',
        'data visualization',
        '3d programming',
        'pass the pen',
        'creative tech',
        'linear algebra',
        'perlin noise',
        'vector',
        'desmos',
        'animation',
        'physics',
        'symbols',
        'movement',
        'trigonometry',
        'matrices',
        'bezier curves',
        'procedural generation',
        'fractals',
        'l-systems',
        'interpolation',
        'openprocessing',
        'algorithmic designs',
        'processing',
        'p5js',
        'processingjs',
        'dwitter',
        'codedoodl.es',
        'sketches',
        'codepen',
        'raven kwok',
        'visual artist',
        'p5art',
        'echophon',
        'devart',
        'folds2d',
        'w:blut',
        'offf',
        'gray',
        'signal',
        'eyeo',
        'mutek',
        'node',
        'digital',
        'codame',
        'curated',
        'nextart',
        'grow',
        'zkm',
        'ars',
        'technorama',
        'kate',
        'digital',
        'nxt',
        'residencies',
        'fellowships',
        'summer schools',
        'opengl',
        'webgl',
        'canvas',
        'audio visualization',
        'computer vision',
        'visualization research',
        'livecoding',
        'graphics',
        'graphics resources',
        'magic tools',
        'hanecci',
    ];
} ?>